version: "3"

output: prefixed

dotenv:
  - "ui/.env.local"
  - "agent/.env.local"

tasks:
  install:
    desc: "Bootstrap application for local development"
    deps:
      - install_frontend
      - install_sandbox

  install_sandbox:
    desc: "Bootstrap application for sandbox environment"
    deps:
      - install_agent

  install_frontend:
    dir: "frontend"
    interactive: true
    cmds:
      - "pnpm install"

  install_sandbox:
    dir: "agent"
    interactive: true
    cmds:
      - "python3 -m venv venv"
      - cmd: "source venv/bin/activate"
        platforms:
          - darwin
          - linux
      - cmd: "powershell venv/Scripts/Activate.ps1"
        platforms:
          - windows
      - cmd: "venv/bin/python3 -m pip install -r requirements.txt"
        platforms:
          - darwin
          - linux
      - cmd: "venv/Scripts/python -m pip install -r requirements.txt"
        platforms:
          - windows

  dev:
    interactive: true
    deps:
      - dev_frontend
      - dev_sandbox

  dev_frontend:
    dir: "frontend"
    interactive: true
    cmds:
      - "pnpm dev"

  dev_sandbox:
    dir: "agent"
    interactive: true
    cmds:
      - cmd: "source venv/bin/activate"
        platforms:
          - darwin
          - linux
      - cmd: "powershell venv/Scripts/Activate.ps1"
        platforms:
          - windows
      - cmd: "venv/bin/python3 agent.py start"
        platforms:
          - darwin
          - linux
      - cmd: "venv/Scripts/python agent.py start"
        platforms:
          - windows
